server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: mis-admin-bff
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/**

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.mis.gateway: DEBUG
