server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: mis-auth
          uri: http://localhost:8101
          order: -10
          predicates:
            - Path=/api/v1/auth/**
        - id: mis-admin-bff
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/**
