# Nacos config: mis-org (prod)
server:
  port: 8103

mis:
  org:
    iam-discovery-enabled: true
    iam-service-id: mis-iam
    iam-base-url: http://mis-iam:8102
    data-scope-skip-when-anonymous: false
