import os, sys

svc_path = r'D:\\code\\mis-platform\\backend\\mis-org\\src\\main\\java\\com\\mis\\org\\service\\DataSetScopeService.java'

lines = []
lines.append('package com.mis.org.service;')
lines.append('')
lines.append('import com.mis.common.core.exception.BusinessException;')
lines.append('import com.mis.common.core.result.Result;')
lines.append('import com.mis.common.core.result.ResultCode;')
lines.append('import com.mis.org.client.IamDataScopeClient;')
lines.append('import com.mis.org.client.IamDataScopeClient.DataScopePayload;')
lines.append('import com.mis.org.config.OrgProperties;')
lines.append('import com.mis.org.domain.entity.SysDept;')
lines.append('import com.mis.org.domain.entity.SysEmployeePost;')
lines.append('import com.mis.org.domain.repository.SysDeptRepository;')
lines.append('import com.mis.org.domain.repository.SysEmployeePostRepository;')
lines.append('import com.mis.org.domain.repository.SysEmployeeRepository;')
lines.append('import com.mis.org.dto.UserDataSetScopeVO;')
lines.append('import com.mis.org.dto.UserDataSetScopeVO.DeptAnchor;')
lines.append('import org.slf4j.Logger;')
lines.append('import org.slf4j.LoggerFactory;')
lines.append('import org.springframework.beans.factory.annotation.Qualifier;')
lines.append('import org.springframework.core.ParameterizedTypeReference;')
lines.append('import org.springframework.stereotype.Service;')
lines.append('import org.springframework.transaction.annotation.Transactional;')
lines.append('import org.springframework.web.client.RestClient;')
lines.append('import org.springframework.web.client.RestClientException;')
lines.append('')
lines.append('import java.util.ArrayList;')
lines.append('import java.util.HashSet;')
lines.append('import java.util.List;')
lines.append('import java.util.Set;')
lines.append('')
lines.append('/**')
lines.append(' * \\u4e3a\\u95ee\\u6570 Worker \\u51c6\\u5907\\u7684\\u7528\\u6237\\u6570\\u636e\\u8303\\u56f4\\u89c6\\u56fe\\u3002')
lines.append(' */')
lines.append('@Service')
lines.append('public class DataSetScopeService {')
lines.append('')
lines.append('    private static final Logger log = LoggerFactory.getLogger(DataSetScopeService.class);')
lines.append('')
lines.append('    private final IamDataScopeClient iamDataScopeClient;')
lines.append('    private final SysDeptRepository deptRepository;')
lines.append('    private final SysEmployeeRepository employeeRepository;')
lines.append('    private final SysEmployeePostRepository employeePostRepository;')
lines.append('    private final RestClient iamRestClient;')
lines.append('')
lines.append('    public DataSetScopeService(')
lines.append('            IamDataScopeClient iamDataScopeClient,')
lines.append('            SysDeptRepository deptRepository,')
lines.append('            SysEmployeeRepository employeeRepository,')
lines.append('            SysEmployeePostRepository employeePostRepository,')
lines.append('            OrgProperties properties) {')
lines.append('        this.iamDataScopeClient = iamDataScopeClient;')
lines.append('        this.deptRepository = deptRepository;')
lines.append('        this.employeeRepository = employeeRepository;')
lines.append('        this.employeePostRepository = employeePostRepository;')
lines.append('        String baseUrl = properties.isIamDiscoveryEnabled()')
lines.append('                ? \"http://\" + properties.getIamServiceId()')
lines.append('                : properties.getIamBaseUrl();')
lines.append('        this.iamRestClient = RestClient.builder().baseUrl(baseUrl).build();')
lines.append('    }')
lines.append('')
lines.append('    @Transactional(readOnly = true)')
lines.append('    public UserDataSetScopeVO getUserDataSetScope(Long userId) {')
lines.append('        DataScopePayload payload;')
lines.append('        try {')
lines.append('            payload = iamDataScopeClient.resolveDataScope(userId);')
lines.append('        } catch (Exception e) {')
lines.append('            log.warn(\"calling mis-iam data-scope failed: userId={}\", userId, e);')
lines.append('            throw new BusinessException(ResultCode.INTERNAL_ERROR, \"cannot resolve user data scope\");')
lines.append('        }')
lines.append('        int dataScope = payload.dataScope();')
lines.append('        boolean isAll = dataScope == 1;')
lines.append('        List<Long> orgIds = payload.customOrgIds();')
lines.append('        List<Long> customDeptIds = payload.customDeptIds();')
lines.append('        List<Long> storeIds = payload.customStoreIds();')
lines.append('        if (isAll) {')
lines.append('            return new UserDataSetScopeVO(userId, dataScope, true, List.of(), List.of(), List.of(), List.of(),')
lines.append('                    storeIds != null ? storeIds : List.of());')
lines.append('        }')
lines.append('        Set<Long> assignedDeptIds = resolveAssignedDeptIds(userId);')
lines.append('        List<Long> effectiveDeptIds = new ArrayList<>(assignedDeptIds);')
lines.append('        if (effectiveDeptIds.isEmpty() && customDeptIds != null && !customDeptIds.isEmpty()) {')
lines.append('            effectiveDeptIds.addAll(customDeptIds);')
lines.append('        }')
lines.append('        if (effectiveDeptIds.isEmpty() && (storeIds == null || storeIds.isEmpty())) {')
lines.append('            return new UserDataSetScopeVO(userId, dataScope, false, orgIds, List.of(), List.of(), List.of(),')
lines.append('                    storeIds != null ? storeIds : List.of());')
lines.append('        }')
lines.append('        Set<Long> subtreeIds = computeSubtreeIds(effectiveDeptIds);')
lines.append('        List<DeptAnchor> anchors = buildDeptAnchors(effectiveDeptIds, customDeptIds, subtreeIds);')
lines.append('        return new UserDataSetScopeVO(userId, dataScope, false, orgIds, effectiveDeptIds,')
lines.append('                new ArrayList<>(subtreeIds), anchors,')
lines.append('                storeIds != null ? storeIds : List.of());')
lines.append('    }')
lines.append('')
lines.append('    private Set<Long> resolveAssignedDeptIds(Long userId) {')
lines.append('        Long employeeId = resolveEmployeeIdByUserId(userId);')
lines.append('        if (employeeId == null) return Set.of();')
lines.append('        Set<Long> deptIds = new HashSet<>();')
lines.append('        employeeRepository.findById(employeeId).ifPresent(emp -> {')
lines.append('            if (emp.getDeptId() != null) deptIds.add(emp.getDeptId());')
lines.append('        });')
lines.append('        List<SysEmployeePost> posts = employeePostRepository.findByEmployeeIdOrderByEffectiveStartAsc(employeeId);')
lines.append('        for (SysEmployeePost post : posts) {')
lines.append('            if (post.getDeptId() != null) deptIds.add(post.getDeptId());')
lines.append('        }')
lines.append('        return deptIds;')
lines.append('    }')
lines.append('')
lines.append('    private Long resolveEmployeeIdByUserId(Long userId) {')
lines.append('        try {')
lines.append('            Result<Long> result = iamRestClient.get()')
lines.append('                    .uri(\"/internal/v1/users/{id}/employee-id\", userId)')
lines.append('                    .retrieve()')
lines.append('                    .body(new ParameterizedTypeReference<Result<Long>>() {});')
lines.append('            if (result != null && result.isSuccess() && result.getData() != null) {')
lines.append('                return result.getData();')
lines.append('            }')
lines.append('        } catch (RestClientException e) {')
lines.append('            log.warn(\"querying employeeId from mis-iam failed: userId={}\", userId, e);')
lines.append('        }')
lines.append('        return null;')
lines.append('    }')
lines.append('')
lines.append('    private Set<Long> computeSubtreeIds(List<Long> deptIds) {')
lines.append('        Set<Long> ids = new HashSet<>();')
lines.append('        for (Long deptId : deptIds) {')
lines.append('            SysDept dept = deptRepository.findById(deptId).orElse(null);')
lines.append('            if (dept == null) continue;')
lines.append('            ids.add(deptId);')
lines.append('            try { ids.addAll(deptRepository.findDescendantIdsById(deptId)); }')
lines.append('            catch (Exception e) { /* tolerant */ }')
lines.append('        }')
lines.append('        return ids;')
lines.append('    }')
lines.append('')
lines.append('    private List<DeptAnchor> buildDeptAnchors(List<Long> effectiveDeptIds, List<Long> customDeptIds, Set<Long> subtreeIds) {')
lines.append('        List<DeptAnchor> anchors = new ArrayList<>();')
lines.append('        for (Long deptId : effectiveDeptIds) {')
lines.append('            SysDept dept = deptRepository.findById(deptId).orElse(null);')
lines.append('            if (dept == null) continue;')
lines.append('            String scope;')
lines.append('            if (customDeptIds != null && customDeptIds.contains(deptId)) {')
lines.append('                scope = \"dept\";')
lines.append('            } else if (subtreeIds.size() > effectiveDeptIds.size()) {')
lines.append('                scope = \"dept_subtree\";')
lines.append('            } else {')
lines.append('                scope = \"org_scope\";')
lines.append('            }')
lines.append('            anchors.add(new DeptAnchor(deptId, dept.getDeptPath(), scope));')
lines.append('        }')
lines.append('        return anchors;')
lines.append('    }')
lines.append('}')

with open(svc_path, 'w', encoding='utf-8') as f:
    f.write(chr(10).join(lines) + chr(10))

print('DataSetScopeService.java written:', len(lines), 'lines')
