import {
  Activity,
  AppWindow,
  BarChart3,
  BookOpen,
  Bot,
  Boxes,
  Building2,
  Cable,
  ClipboardCheck,
  ClipboardList,
  Cpu,
  Crosshair,
  Database,
  FileText,
  FolderTree,
  GitBranch,
  Globe,
  History,
  Home,
  KeyRound,
  Languages,
  LayoutDashboard,
  ListTree,
  Lock,
  LogIn,
  Menu,
  MessageSquare,
  MessagesSquare,
  Network,
  Plug,
  Route,
  Settings,
  Shield,
  ShieldCheck,
  Sparkles,
  UserCog,
  Users,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  LayoutDashboard,
  Settings,
  Users,
  Building2,
  Shield,
  Home,
  GitBranch,
  Menu,
  BookOpen,
  LogIn,
  FileText,
  Network,
  FolderTree,
  Globe,
  UserCog,
  AppWindow,
  Cable,
  KeyRound,
  ListTree,
  Activity,
  ClipboardList,
  // 知识库子系统（V13__kb_seed.sql 中 sys_menu.icon 取值）
  Database,
  Lock,
  Sparkles,
  BarChart3,
  Cpu,
  // Wave D：命中测试（Crosshair 在 WA-08 即已使用，这里补登记以免被 eslint 报未使用导入）
  Crosshair,
  // Wave D：同义词管理（Languages，V18 seed）
  Languages,
  // 智能体运营控制台（V19__agent_ops_seed.sql 的 sys_menu.icon 取值 + V21 的 ShieldCheck）
  // 缺登记不会报错，只会静默回退成 LayoutDashboard —— 侧栏 12 个菜单图标全一样。
  Bot,
  MessageSquare,
  History,
  Boxes,
  Route,
  Plug,
  MessagesSquare,
  ClipboardCheck,
  ShieldCheck,
};

export function resolveNavIcon(name?: string | null): LucideIcon {
  if (!name) return LayoutDashboard;
  return ICON_MAP[name] ?? LayoutDashboard;
}
