server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: mis-auth
          uri: http://mis-auth:8101
          order: -10
          predicates:
            - Path=/api/v1/auth/**
        - id: mis-admin-bff
          uri: http://mis-admin-bff:8081
          predicates:
            - Path=/api/v1/**

mis:
  security:
    gateway:
      enabled: true
    jwt:
      public-key-path: ${JWT_PUBLIC_KEY_PATH:/etc/mis/keys/public.pem}
